### ISSUE TITLE
Logging in and sync files for long times in Arch Linux MEGAsync desktop client

### ISSUE THREAD

**Issue by fgoinai** [meganz/MEGAsync#122]
- MEGAsync ver
  + 3.1.4(0065d1)
- OS ver
  + Arch Linux 4.12.8-2 x86_64
- Symptom
  + take 24 hrs to login
  + take few hrs to sync few files which is few KB each only
- Solution tried
  + Use other network under different ISP
    * Not work
  + Reinstall MEGASync from AUR
    * Not work
  + Clear all config and reinstall MEGASync from AUR
    * Not work
  + Download from mega.nz and reinstall
    * Not work
  + Re-login
    * Not work
- Log
  + No log could be found either in journalctl or /var/log

Anything I can do to solve this issue?

**Comment by polmr** [comment]
We found some issues related to the latest update in curl in Arch Linux. However they should be solved with the latest version available at mega.nz/sync, since we are no longer linking curl dinamically. Just to be 100% sure. Ensure your `megasync` executable is not linking curl dinamically. This should be empty:
```
ldd `which megasync` | grep curl
```
Also, you can try to disable HTTP for transfers (Settings -> Bandwidth -> Don't use HTTP). If you still have issues, please generate a log so that we can determine what's happening. 
In order to do so: please close MEGAsync, and run it in a terminal in this way while reproducing your issues:

megasync --debug > log.txt

Since the log could contain sensitive data (mainly file names) it would be better if you 
send it to support@mega.nz along with the the URL of this issue on GitHub. 
That way, the report should reach the developmenent team fast and we would carefully review it.

**Comment by fgoinai** [comment]
Today I have reinstalled the MEGAsync client from AUR and it works fine now

Some points:
- version remains
- ldd shows "libcurl.so.4 => /usr/lib/libcurl.so.4 (0x00007fadb879a000)"
- small file syncing issue solved

Thanks a lot with your help!
