### ISSUE TITLE
Doesn't work on Fedora 24

### ISSUE THREAD

**Issue by srakitnican** [meganz/MEGAsync#13]
Fedora 24 is currently in alpha and since MEGAsync builds are not available for it yet, packages for fedora 23 doesn't work, maybe related to Fedora 24 being moved to use gcc compiler version 6?

**Comment by polmr** [comment]
Thanks for pointing it out srakitnican. Some dependency might have changed. We will be working on providing a version for Fedora24 asap.

**Comment by polmr** [comment]
There already is a version for Fedora 24 64 bits. You can download it from: https://mega.nz/#sync

**Comment by jknetl** [comment]
Fedora 24 is not listed when choosing distribution on the website: https://mega.nz/#sync

So I didn't know there is a package for Fedora 24 and I ended up with package for 23 which obivously wasn't working. I has found out because of this issue that there should be a package for 24. You may find it here: https://mega.nz/linux/MEGAsync/Fedora_24/x86_64/

Please add the Fedora 24 option to the list to avoid problems for other users.

**Comment by polmr** [comment]
will do. Thanks for reporting @jknetl ;-)
