### ISSUE TITLE
Sync client status icon distorted in linux after recent update

### ISSUE THREAD

**Issue by subhammridha** [meganz/MEGAsync#141]
I am using CentOS 7.4. Recently the MegaSync client was updated to version 3.5-1.1. After that the sync 
client status icon looks distorted as shown in the following image:
![image](https://user-images.githubusercontent.com/16416796/32892513-5bf82004-cace-11e7-9b8c-0018dbd0f8fb.png)

Please note that I am using gnome's top icon extension. If I turn off that extension, the status icon looks fine as shown below:
![image](https://user-images.githubusercontent.com/16416796/32892625-c83aaa20-cace-11e7-99e7-44ecf7282177.png)

In my opinion that should not be a problem as the earlier version used to work fine in both the scenarios.

Kindly help me fix this.

**Comment by polmr** [comment]
I've just installed a CentOS with gnome-shell + TopIcons Plus. M is not distorted in my case. However, playing with icon size in TopIcons configuration (in Tweak Tool -> Extension -> TopIcons plus cogwheel), I've been able to get some distortion when modifying the size of the icons.
In MEGAsync 3.5 we have started using icons installed in the system instead of hardcoded ones. If you remove the installed ones and restart MEGASync, it'll fallback to hardcoded ones. This seems to disable distortion. The "ability" to be distorted should be an option on the theme configuration file of your particular desktop environment. 
FYI, the icons installed by MEGAsync are located at:  
```
/usr/share/icons/hicolor/scalable/status/megalogging.svg
/usr/share/icons/hicolor/scalable/status/megapaused.svg
/usr/share/icons/hicolor/scalable/status/megasynching.svg
/usr/share/icons/hicolor/scalable/status/megauptodate.svg
/usr/share/icons/hicolor/scalable/status/megawarning.svg
```

**Comment by subhammridha** [comment]
@polmr, you were correct that if I disable the system icons (from /usr/share/icons...) the icon distortion seems to go away. 

But, weirdly in my case, if I disable the builtin topicon plugin and use the topicon plus plugin (as mentioned by you), MEGAsync status icon is not distorted. This is true even when I use the system icons, i.e., from /usr/share/icons/...

I don't understand what exactly the problem might be.

**Comment by polmr** [comment]
Seems like TopIcons is trying to paint the tray icon with the wrong proportions, when scaling is enabled (icons from /usr/share/icons/....) . Is good to know TopIcons plus behaves ok. We'll try to find out if there's anything we can do to prevent the issue with regular "TopIcons" ...

**Comment by subhammridha** [comment]
Recently I switched to using the gnome dash-to-panel plugin. Here as well, the megasync icon is distorted.

![image](https://user-images.githubusercontent.com/16416796/40476742-4eb5bd16-5f34-11e8-9e67-065bec762db2.png)

I was searching for some other references on status icon distortion and found [this link](https://github.com/home-sweet-gnome/dash-to-panel/issues/87).

It seems that GNOME is the culprit which is unable to display svg icons properly.

That said, I don't think keeping this issue open is wise as it is not related to megasync. Thanks for your help anyway.
