### ISSUE TITLE
Megasync window pops up at startup (i3-wm)

### ISSUE THREAD

**Issue by thurse93** [meganz/MEGAsync#142]
Hi!

im using megasync and the i3 window manager. Since the latest release the "sync status window" pops up every time im starting the system and/or megasync. Can i suppress the creation of this window somehow?

I'm not using any kind of system tray by the way.

**Comment by polmr** [comment]
This is an intended behaviour so that users can access the interface and are aware that MEGASync is running in the absence of a system tray icon.  There's no way to suppress that. There are some tools to minimize a window from the command line (xdotool, wmctrl, ... ). You might be able to automatize it with them.

**Comment by ggkr** [comment]
Hi.

the majority of programs (that start with windows) enable users to choose the start behavior. personally I like the 'set up and forget' behavior in which I don't have popup coming up on my computer. please add a 'start minimized' option to startup.

**Comment by brownem** [comment]
I would also prefer a 'start minimized. option. In fact, I think it used to for me until this past week or so, not sure what changed (probably a Windows update that messed with an adjustment I made). Having this built into the app, instead of something users have to 'hack' into the program's behavior would be really nice.

**Comment by Surendrajat** [comment]
I got a workaround for this in i3-wm https://github.com/meganz/MEGAsync/issues/161#issuecomment-797917923
