### ISSUE TITLE
Ubuntu: couldn't upate to 3.6.0

### ISSUE THREAD

**Issue by repsorp** [meganz/MEGAsync#168]
Hi,

couldn't update to megasync 3.6.0

Terminal messages:
1 package can be upgraded. Run 'apt list --upgradable' to see it.
sudo apt list --upgradable
megasync/unknown 3.6.0-1.1 amd64 [upgradable from: 3.5.3-2.1]
N: There is 1 additional version. Please use the '-a' switch to see it
sudo apt list --upgradable -a
megasync/unknown 3.6.0-1.1 amd64 [upgradable from: 3.5.3-2.1]
megasync/now 3.5.3-2.1 amd64 [installed,upgradable to: 3.6.0-1.1]

sudo apt upgrade
The following packages have been kept back:
  megasync
0 upgraded, 0 newly installed, 0 to remove and 1 not upgraded.

Synaptic tells me upgrading also affects other packcages:
![synaptic](https://user-images.githubusercontent.com/6297032/36342902-5a437864-1405-11e8-8007-2c8e803cf025.png)

What can I do ?

Thanks for help

config:
ubuntu 16.04
megasync 3.5.3

**Comment by polmr** [comment]
MEGAsync since the last version depends on libmediainfo0v5 and libzen0v5. Both packages are provided by the official `universe` repository. It seems that those packages conflict with those libmediainfo0 & libzen0 you appear to have already installed in your system. You must have gotten them from somewhere else (probably a third party repo). mediainfo & selene packages depend on those 2 libraries. `mediainfo` package is available in `universe` repo too. You  can reinstall it afterwards. For `selene` you might want to try ignoring dependencies and hoping it works fine with official libmediainfo & libzen:
You can try the --nodeps flag with apt-get.
Or download the package and install it using dpkg with the option --ignore-depends.

**Comment by repsorp** [comment]
Perfect
Thanks

**Comment by repsorp** [comment]
Perfect
Thanks

**Comment by ZamanOof** [comment]
I get this error 
`megasync: error while loading shared libraries: libcrypto++.so.6: cannot open shared object file: No such file or directory
`
try to install 
`sudo apt install libcrypto++6`
worked for me as **Ubuntu 18.04.3 LTS**
Best Regards
