### ISSUE TITLE
Windows Client stopped syncing automatically - now requires restart with full scan to sync

### ISSUE THREAD

**Issue by jakobrosenberg** [meganz/MEGAsync#19]
Noticed the issue a few days ago.

**Comment by javiserrano** [comment]
Thank you for your report.

In order to investigate the problem, we would need to know your operating system (Windows, OSX, Linux) the version of MEGAsync that you are using and, if possible, detailed steps to reproduce it.

If the problem is not reproducible in another computer, it would be very useful for us to have a debug log showing the problem. To start MEGAsync in debug mode, keep Ctrl+Shift (Cmd+Shift on Mac) pressed while MEGAsync is starting and it will create a log in your desktop. 

The log could contain sensitive data (file names, paths, etc.), so it would be better to not post it publicly here and send it by email to our support team (support@mega.nz). They would forward it to our development team.

**Comment by jakobrosenberg** [comment]
Version is 2.9.5

Starting Megasync with admin rights generated no new log file. The startup time however was much longer than usual and realtime syncing is working.

**Comment by vtmateos** [comment]
Dear users,

In case you experience any related issue with latest 5.6.1 version, feel free to create a new ticket so the dev team can provide proper support.

Thanks for your report.
