### ISSUE TITLE
Broken ArchLinux i686 arch repo

### ISSUE THREAD

**Issue by WyRe** [meganz/MEGAsync#204]
I'm getting error messages when I try upgrade the system, kind of

`failed retrieving file 'DEB_Arch_Extra.db' from mega.nz : The requested URL returned error: 404`

I suspect do you have abandoned i686 architecture development because ArchLinux have abandoned the i686 architecture too; I'm using [this ArchLinux fork](https://archlinux32.org/); what do you think about reconsider keep working on 32bit version? 

Thank you.

**Comment by polmr** [comment]
That's right. We will reconsider that. In the meantime, you can always build MEGAsync yourself using the instructions here: https://github.com/meganz/MEGAsync, and PKGBUILD will surely come handy to you too: https://github.com/meganz/MEGAsync/blob/master/build/templates/MEGAsync/PKGBUILD. Also, there's the community supported https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=megasync (beware this is not officially supported, use it at your own risk )

**Comment by WyRe** [comment]
@polmr Thank you, one more time ;-) 

Since I don't need package 64bit version ... should I remove `'x86_64'` value from `arch=()` array, right?

**Comment by polmr** [comment]
Sure you can remove it, but AFAIK it won't be necessary.

**Comment by WyRe** [comment]
@polmr it is not necessary, right, but I would like to reduce the packaging time, since I don't need the 64bit version xD

**Comment by WyRe** [comment]
@polmr a few more questions, 

What do you think about this two [megasync](https://aur.archlinux.org/packages/megasync) and [megasync-git](https://aur.archlinux.org/packages/megasync-git/) different packages? 

How could I check when would be necessary repackage megasync, checking versions? megasync-git version is based on this code, is not easy compare it with megasync package version. I think megasync-git uses master branch and megasync uses linux version tree, right?

**Comment by polmr** [comment]
`uses linux version tree`? having a quick look at it, the `megasync` uses a fixed tag. This requires updating whenvever a new release is done. `megasync-git`  get's whatever is in `master` HEAD and determines what the version number is by reading the last tag. For the first one you'd need to manually update the version in order to build again whenever a new version is published to the repo. `megasync-git` always get's the last commit in `master`, you don't need to update: just rebuild it, but you lose control as to what commit is being built.
