### ISSUE TITLE
MEGAsync freezes Cinnamon taskbar

### ISSUE THREAD

**Issue by ZacDiggum** [meganz/MEGAsync#23]
Hi,
recently I upgraded from Linux Mint 17.3 to 18 running Cinnamon 3.0.7. When clicking the MEGAsync taskbar icon most of the times the little window opening up freezes the whole taskbar so that the MEGAsync window won't disappear after clicking elsewhere and I'm unable to click other taskbar icons. Then I usually click on  'end MEGAsync' and choose 'No'  in the dialogue. Then the taskbar is unfrozen again.

**Comment by polmr** [comment]
@ZacDiggum could you try to uninstall megasync and install the Mint 18 version of megasync (available at https://mega.nz/#sync) and see if the problem persists?

**Comment by ZacDiggum** [comment]
That's what I did. To clarify: I did a clean install of LM 18 Cinnamon and got MEGAsync from mega.nz. Version is 2.9.5(f19d). Graphics stack is AMDs new open source driver, amdgpu (non -pro).

**Comment by polmr** [comment]
I'm unable to reproduce... Where do you exactly click on 'end MEGAsync' (there shouldn't be any 'end Megasync' anywhere on the UI), which dialog are you refering to. Please, would you care to elaborate a little bit on that.

**Comment by ZacDiggum** [comment]
Of course. Clicking on the taskbar icon and 'show status' I get the MEGAsync window (with the white background and latest transfers and so on). In this window I click the little gear wheel in the upper right corner which gives access to 'about MEGAsync', 'upload', 'download' and 'preferences'. Clicking any of these closes the main window and opens the respective new window, for example 'preferences' with a grey background. This closing the main window and opening a new window unfreezes the whole thing. So I think the problem is about the (white background) main window. I think I'll take a look at the Cinnamon forums if maybe other taskbar icons have similar problems.

**Comment by ZacDiggum** [comment]
Oh, and I use an old Radeon HD 7750 with AMD's amdgpu driver, which was installed as default when installing Mint 18. Maybe this one still has some rough edges?

**Comment by polmr** [comment]
Quite strange. Bear in mind that Mint 18 is something rather new. It sounds like an issue with QT and Cinnamon... Freezing the entire taskbar is not something megasync does (nor is able to do). Ensure you have QT updated. Also, installing the package `sni-qt` might help. If it doesn't maybe we can check if Qt is reporting some error. Run megasync from a console with ```megasync --debug > megasync.log``` and try to reproduce the issue. Once you've done so, please send the log to us so that we try to analyse it. If you don't want to share it here (it could contain sensitive data like filenames, etc.), please send it to support@mega.nz and post here the ticked ID (you will receive a response with this ID) so we can contact our support team to get your log. If you find some related information in Cinnamon forums don't hesitate to put it here, so that others may benefit from it.

**Comment by ZacDiggum** [comment]
sni-qt is already installed. Qt versions installed are 4.8.7 and 5.5.1. 
There's only one message related to Qt. The very first log line says:
QT Warning: QSystemTrayIcon::setVisible: No Icon set
Of course, the red M icon appears in the taskbar...I'll post an issue over at Cinnamon. I've seen at launchpad, that Cinnamon has a very long history of freezing taskbars, so the problem should be on their side.
Please leave this issue open for now, since I'd like to link to it on Cinnamon's github page.

**Comment by ZacDiggum** [comment]
Update: Okay, the people over at the Cinnamon repo didn't respond...I think the problem is related to Cinnamon and the new amdgpu open source driver for AMD GPUs. Freezing occurs on my desktop system with amdgpu but not on my laptop with an integrated Intel GPU. I'll close this issue now.
