### ISSUE TITLE
 Missing dolphin-megasync 3.6.6 in AUR Archlinux

### ISSUE THREAD

**Issue by acutbal** [meganz/MEGAsync#248]
Hi. In AUR I can't find dolphin-megasync-3.6.6-2, there is only a git version. Could you fix this? Thank you very much.

Cheers, :smiley: 

Albert.
![screenshot_20181128_120648](https://user-images.githubusercontent.com/2278584/49147863-20c5fe00-f306-11e8-8fe8-59a107d04c24.png)

**Comment by polmr** [comment]
Official packages for MEGAsync are provided here: https:/mega.nz/sync. Once you install MEGAsync you can install dolphin extension with `pacman -Sy dolphin-megasync` since the corresponding repo will be configured. Alternatively you can browse and download dolphin extension package here: https://mega.nz/linux/MEGAsync/Arch_Extra/x86_64/

**Comment by acutbal** [comment]
Installed, thank you so much!! :smile:
