### ISSUE TITLE
FreeBSD compatibility

### ISSUE THREAD

**Issue by dakk** [meganz/MEGAsync#277]
Does megasync supports freebsd? If not, is it planned to add support for freebsd?

I tried to compile on freebsd from source but I found many problems with the process; I also tried to run a linux binary with linux-compat-layer but no luck. (Currently I'm using the windows version using wine and it's doing the job)

**Comment by nkosi23** [comment]
I am interested in this too

**Comment by polmr** [comment]
This would require to circumvent the lack of inotify support in FreeBSD. The alternative kqueue has some drawbacks and would require quite some efforts to have it included in our sync engine. So, for the moment, FreeBSD is not expected to be supported I'm afraid.

**Comment by nkosi23** [comment]
Just for future reference when this comes in the radar

https://github.com/libinotify-kqueue/libinotify-kqueue

This is the most mature library implementing a libnotify api on top of kqueue. That being said, looking at the Readme, I think it would scale badly on large accounts since it opens a file descriptor to manage quite a lot of events (due to kqueue).

**Comment by dakk** [comment]
I get MEGASync compiled on freebsd; the real problem is not inotify (which works perfectly with the kqueue bindings), but the source of mega which has no #ifdef for freebsd include files

**Comment by nupfel** [comment]
@dakk can you share a patch of your work to get it to compile and run on freebsd, please?

**Comment by dakk** [comment]
@nupfel https://github.com/dakk/MEGAsync it is a bit outdated now
