### ISSUE TITLE
New line doesn't work in QMessageBox on Windows

### ISSUE THREAD

**Issue by ayancey** [meganz/MEGAsync#31]
Looks like [this](http://i.imgur.com/MhyAUEw.png). Code is [here](https://github.com/meganz/MEGAsync/blob/master/src/MEGASync/MegaApplication.cpp#L1424).

**Comment by Logic-gate** [comment]
Nice catch. 

Although it's kind of weird that it didn't render the line break. I suppose a space before the first`\n` might do the trick, or a simple html style `<br>`.

**Comment by javiserrano** [comment]
`\n` should work. The problem seems to be that our translation to English (the strings in the code are just "keys") doesn't contain the `\n`.
https://github.com/meganz/MEGAsync/blob/master/src/MEGASync/gui/translations/MEGASyncStrings_en.ts#L759

Translation files are autogenerated in a different platform and not directly managed by developers so we can't fix it here. But we will inform our tranlation team to get it fixed or will replace the original string to get a correct translation for the next update.

**Comment by ayancey** [comment]
@javiserrano My mistake. Thank you for the prompt update! I feel silly for submitting such a trivial issue, but someone has to do it.

**Comment by javiserrano** [comment]
Don't worry. It's perfectly OK! We need to see the problems in order to fix them :-) so any report is welcome. Despite it's not possible to see it here (the development is made in a private repo and we push all commits to this one every time we release a new version) we have changed the string, so in the next version it should be fixed.
