### ISSUE TITLE
MEGA File Manager integration dosen't work

### ISSUE THREAD

**Issue by edgren** [meganz/MEGAsync#312]
Hi!

I am on elementary OS 5.0 Juno and have MEGAsync installed, but I want to replace MEGAsync with MEGA File manager integration, so I can manage my cloud storage without taking any internal storage.

I've installed the integration for Nautilus (Files) but nothing happens after the installation are completed. Do I have to do something afterwards? There are no guides how to setup this integration. Plus, I am new to Linux after my whole life using Windows.

**Comment by polmr** [comment]
Hi @edgren 
The file manager integrator (in your case `nautilus-megasync`) is intended to work with MEGAsync. It needs MEGAsync to be running in order to work. You will also need to restart `nautilus` (simply closing all nautilus windows might not be sufficient, so you might want to issue `killall nautilus` in a shell). Once you have MEGAsync running and nautilus restarted, you will be able to interact with MEGA within your file browser. On one hand, you will see a submenu when you right click on a file/folder. That will give you options for uploading to MEGA, or if you are within a folder that's synched via MEGAsync, you will be able to open the selected element in MEGA (using the web client) or get a shareable link to your file/folder. On the other hand, you will see some overlay icons on top of the files/folders within a synched folder, that will indicate the status (synched with a green thick mark, synching a blue circle, or a red X if something's wrong).

**Comment by edgren** [comment]
Thank you for your answer.

I did use the command `killall nautilus` but the process was not found, even if the file manager was in the background. I tested to run all the file managers that were listen on mega.nz/sync while the file manager was in the background, but none of them had processes to kill. I use the standard file manager that comes with elementary OS 5.0 Juno. I tested Polo few weeks ago, but I didn't like the startup delay, so I uninstalled it.

**Comment by polmr** [comment]
ok @edgren , let's try to throw some light here. Elementary OS uses its own file browser: `io.elementary.files` which is named `Files`. In order to use MEGA File Manager integrations you will need to launch nautilus browser (which sadly is also named `Files` in Elementary OS). There's no specific extension for Elementary OS Files.
Apologies for the delayed response. Hope you can start using a file browser that integrates with MEGA.

**Comment by edgren** [comment]
Ah, that is a bummer :) Anyway, thank you for the clarification. Will try other file managers or Linux distributions.
