### ISSUE TITLE
Problems with crypto++ 5.6.4

### ISSUE THREAD

**Issue by Enawa** [meganz/MEGAsync#35]
MEGAsync don't start.
```
#0  0x00007f1598b9c398 _ZN8CryptoPP16IteratedHashBaseIjNS_18HashTransformationEE14TruncatedFinalEPhm (libcryptopp.so)
#1  0x00007f1598b38c9a _ZN8CryptoPP10RandomPool18IncorporateEntropyEPKhm (libcryptopp.so)
#2  0x00007f1598c69773 _ZN8CryptoPP20AutoSeededRandomPool6ReseedEbj (libcryptopp.so)
#3  0x0000000000436945 n/a (megasync)
#4  0x000000000066b6ed n/a (megasync)
#5  0x00007f1595531220 __libc_start_main (libc.so.6)
#6  0x0000000000438cd9 n/a (megasync)
```

**Comment by polmr** [comment]
Hi @Enawa, Would you care to elaborate a bit on your issue please? Are you compiling megasync yourself? (if affirmative... which steps are you following?) Are you trying to run a precompiled megasync on a system with cryptopp 5.6.4? (in such case which system are you using, how did you end up with cryptopp 5.6.4, ...)

**Comment by gabretana** [comment]
I can confirm that happen with version 2.9.8 of MEGASync (precompiled) and version 5.6.4 of crypto++

**Comment by polmr** [comment]
I am guessing you are using Arch Linux package downloaded from https://mega.nz/#sync.
The problem was that they have updated cryptopp version and megasync was linked against 5.6.3 (5.6.4 seems to lack backwards compatibility). The megasync package has just been updated and the problem should be solved now. You can either download it again or update directly with <pre>pacman -S megasync</pre>If your are not using the Arch Linux package or encounter any problem, please let me now. Thanks for reporting.

**Comment by gabretana** [comment]
@polmr Yes I'm using Arch and just updated package from repo and now works fine, thank you very much
