### ISSUE TITLE
got stuck downloading files

### ISSUE THREAD

**Issue by usama7628674** [meganz/MEGAsync#357]
![Capture](https://user-images.githubusercontent.com/29252277/66283061-716d9680-e8db-11e9-9282-75ac78899ce7.PNG)

Happens all the time.Please fix it

**Comment by mattw-mega** [comment]
Hi usama7628674, could you please check if you're using the latest version, 4.2.5.  If so please collect logs from MEGAsync to help us diagnose the problem here.   When the problem occurs, open settings, and click on your user avatar icon 5 times to start logging (it appends to MEGAsync.log in the desktop).   Wait for a few minutes so that the retries will have occurred and been logged.  Click 5 times again to stop logging.    If you could send the log to support@mega.nz and post the ticket number here.  First remove any info from the log that you're not happy to share, of course.   And if it's the same file failing over and over, send us a link to that file so we can look into it (though it sounds like it's random files?)  thanks

**Comment by lavancig** [comment]
I am facing the same problem. A log of the occurence is attached here. 
Internet connection was surely not an issue.
[MEGAsync.log](https://github.com/meganz/MEGAsync/files/3740362/MEGAsync.log)

**Comment by mattw-mega** [comment]
Hi lavancig, thanks for posting the log.   It shows MEGAsync asking the servers for a URL to upload the file to, but the servers respond with -3 (busy).   We think you must have started a very large operation prior to this, such as a move of a huge number of files and folders, and the servers were busy processing that, and could not accept any further requests related to your account until that finished.

**Comment by lavancig** [comment]
Hello @mattw-mega, thank you for the quick reply.
As you can see, the log was collected for a few hours, and almost 12 hours later, the files still have not downloaded.
This is an issue that I am observing in two different machines, in both Linux and Windows.

**Comment by mattw-mega** [comment]
Hi lavancig, thanks very much for the update, and I'm glad your transfers have completed now.  The servers returning -3 would not have been resolved by a client side action such as a full scan though, so I think that may be a coincidence (though, the transfers do wait for longer and longer periods between retries when -3 is received, and the full scan would have cause it to retry again at that time rather than at the end of the wait period, which could have gotten quite large by that time).    Do you remember if you had started a large operation such as moving or copying a folder with a huge number of subfolders and files, before the problems started?  thanks

**Comment by lavancig** [comment]
hello @mattw-mega. This was indeed the case. I was syncronizing (downloading) a folder with several subfolders/small files.
