### ISSUE TITLE
OpenSUSE Tumbleweed upgraded to Crypto++ 5.6.4

### ISSUE THREAD

**Issue by ffhaddad** [meganz/MEGAsync#36]
MEGASync won't install on OpenSUSE Tumbleweed because it's looking for Crypto++ 5.6.2 which was superseded with 5.6.4. I made the necessary changes to support the latest version and can create a pull request if you would like.

**Comment by polmr** [comment]
Hi @ffhaddad, Thanks for noticing. The app offered in the repo and at https://mega.nz/#sync is now fixed and will install just fine. Still, I wonder what are those changes you refer to. Feel free to create the pull request so that we can consider it.

**Comment by ffhaddad** [comment]
Thanks @polmr! Just used the update tool in in SUSE and it worked. BTW, all I did was modify the script `create_tarball.sh` in the build directory to look for 5.6.4 of Crypto++ and updated the MD5 value.

**Comment by polmr** [comment]
Hi @ffhaddad. Glad it worked. Actually in the end we were not downloading any crypto++, but compiling against systems' crypto++ dynamically (which was 5.6.2 and now is 5.6.4). Since thumbleweed is a rolling release and such change is likely to happen again we adopted a similar solution to the one you propose, linking statically. Don't do the PR, but thanks for the inputs anyway ;-).
