### ISSUE TITLE
Respect Qt style

### ISSUE THREAD

**Issue by KottV** [meganz/MEGAsync#38]
Greetings and thank for app.

Is there any way to make Megasync use system-wide Qt style?
I've build Qt4 and Qt5, both renders in some default Qt-style. Not so critical, but ...

**Comment by javiserrano** [comment]
Changing the first paramenter of `QApplication::setDesktopSettingsAware` from `false` to `true` should make MEGAsync to use the system-wide stype. We disabled it because some users reported that some controls were difficult to use with some configurations.

You can find that function here:
https://github.com/meganz/MEGAsync/blob/master/src/MEGASync/MegaApplication.cpp#L158

**Comment by KottV** [comment]
ok
