### ISSUE TITLE
Sync a Folder on External USB Drive 

### ISSUE THREAD

**Issue by steve4444** [meganz/MEGAsync#397]
I would like put one or more sync folders on an external USB drive. This would be very convenient as I could work with a PC without MEGAsync without manually copying files on the USB drive, but simply plugging in & out the USB disk.

What is the proper way to do so? Specifically:     
a) Will MEGA block my USB drive ejection?   
b) Should I stop MEGA to allow ejection?    
c) What if I plug-in a different pen drive without the synced folder or   
d) I want to plug-in a pen to take a file without waiting the possibly long sync.

**Comment by mattw-mega** [comment]
The most important thing is to format your USB drive as NTFS.   Any type of FAT format has problems where the ID of files on the disk change unexpectedly when the drive is reattached to the system, which can occasionally cause problems for MEGAsync.
Additionally, in order to make sure all cloud changes are applied correctly to the USB, only run MEGAsync when the USB is plugged in (and exit it before ejecting the drive).   So quit it before ejecting the USB, and only start it when the USB is plugged in again (you should turn off "start on startup" in the settings dialog to make sure of that).  
If you need to download a file without MEGAsync running, the website can do that by itself.  thanks

**Comment by steve4444** [comment]
Thanks
