### ISSUE TITLE
10175 segmentation fault megasync

### ISSUE THREAD

**Issue by jemadux** [meganz/MEGAsync#42]
I used debian sid and i wanted to make a fresh install with debian testing . in debian sid i used the username angelos and I moved the /home/angelos to /home/jemadux . I desired to use the username jemadux and that is . i tried the deb files that is on mega.zn and says that not working .. so i deleted I guess the data of mega
`
$ rm -rf .local/share/data/Mega\ Limited `

and when from command line start the mega is
```

$ megasync 
[1]    10175 segmentation fault  megasync
```

and i cant connect to server .. do i have to do something elase

**Comment by polmr** [comment]
Hi @jemadux. 
I understand you installed the Debian 9 package. It has been generated with an alpha 7 Stretch (latests available).
The segmentation fault is likely due to a change in cryptopp library. It is compiled against libcryto++ 5.6.3 whereas testing repos offer 5.6.4
Backward compatibility is broken for cryptopp I'm afraid. I think the solution is to release a version with libcrypto linked statically (at least until a final Debian 9 is released). It shouldn't take long, but if you want an inmediate solution that might work, you can compile libcryptopp 5.6.3 and launch megasync with the corresponding LD_LIBRARY_PATH stablished to the path where you compile libcrypto++

**Comment by nunoachenriques** [comment]
hi @polmr, i have the same issue but a bit more clean: megasync just started to segfault after a regular upgrade on my debian gnu/linux stretch (9.0, testing). can you please, please, please :-) give priority to this issue so we all avoid being out of sync for too long...? thanks and cheers!

```
$ megasync --debug
15:16:28 (warn):  QT Warning: QSystemTrayIcon::setVisible: No Icon set
15:16:28 (debug): IPv6 enabled: 1 (net.cpp:61)
15:16:28 (debug): DNS servers: n.n.n.n,n.n.n.n (net.cpp:207)
15:16:28 (warn):  The app was recently restarted. Restart skipped
Segmentation fault
```
additionally, it seems rather strange that a patch (major.minor.patch) increment (3 to 4) causes a backward incompatibility (libcrypto++ folks should pay more attention to versioning ;-)):

> [...] PATCH version when you make backwards-compatible bug fixes.

From: http://semver.org/

**Comment by polmr** [comment]
This is fixed already (only the package for 64 bits). Update megasync package / download it again from https://mega.nz/#sync and the segfault should be solved. Thanks all for reporting.

**Comment by nunoachenriques** [comment]
hi @polmr  and thanks for the fast build!
```
apt-get update
apt-get upgrade
megasync &
```
et voilà! in sync again!
cheers :-)
