### ISSUE TITLE
Extremely slow login and locks up device view (This PC) when MEGA folder on external USB hard drive

### ISSUE THREAD

**Issue by eric-tucker** [meganz/MEGAsync#44]
On Windows 10.

1. Place MEGA folder on external (portable hard drive).
2. Start MEGA.
3. MEGA takes about 60+ seconds to login
4. Meanwhile, open File Explorer - it hangs at This PC with the message "Working on it..."

This does not occur if the MEGA folder is placed on the C drive.  The entire time, the indicator light on the portal hard drive is flashing.  Analyzing the performance tab of task manager shows this is all read activity.

**Comment by javiserrano** [comment]
We have detected that this problem is mainly caused by antivirus software analyzing all files that MEGAsync scans at startup. Adding MEGAsync and synced files to the exclusion list of Windows Defender usually solves the problem. Anyway, we are about to release a new update improving the initial scanning of MEGAsync for a better compatibility with antivirus software. So, with the next update, it shouldn't be needed to add MEGAsync nor the synced files to the exclusion list of antivirus software to solve this problem.

Please, take also into account that MEGAsync needs to read metadata of synced files/folders at startup (type, filesystem id, modification time and size), so if they are in a slow external drive (for example USB 2.0) and the number of synced files is very high. It could take some time to read that metadata.

**Comment by eric-tucker** [comment]
Indeed Windows Defender is the culprit.  Adding the portable hard drive to the exclusion list either before or even DURING MEGA startup solves the issue and allows startup to proceed in about 2 seconds.

Side note: my MEGA folder contains around 14,000 files, so I don't think the USB performance is too much of an issue compared to Windows Defender.

**Comment by javiserrano** [comment]
The new version with better compatibility with antivirus software among other things (MEGAsync 2.9.10) has been already released on the web:
https://mega.nz/#sync

It should improve the startup time even without excluding your portable hard drive. You should receive the autoupdate in few days.
