### ISSUE TITLE
OSX sync client won't connect (or create the log debug file)

### ISSUE THREAD

**Issue by cswanson2** [meganz/MEGAsync#45]
Summary: The MEGAsync Mac client won't log in (although I know the credentials are good) and won't create the log file (that support indicates it should from CMD-SHIFT execute)

Recreate steps:
- I downloaded the file https://mega.nz/MEGAsyncsetup.dmg
- installed it normally, no problems
- execute app - asks for username and password - I use my email address and my pw - I know they work since the Windows client and my web log in works perfectly
- tech support had me try to turn on logging - CMD-SHIFT together then execute - the app loads but no file is created on the desktop - log in fails again
- I tried on 5 other Macs at the office - same thing - no log in, no logs
- I tried at work and at home (same problem) - I tried through my cell phone tether (just in case it was some weird ISP filtering) - same thing

All the failing machines have OSX El Capitan 10.11.5 or 10.11.6 - Macbook Pro 15" late 2013 - fast processor, tons of memory and disk
I don't know any other step to take.

If someone can build a special client version that prints to standard out from command line I can run it from the command line and maybe get more data. I would try and compile it myself but I doubt my success at doing that.

Highly motivated to get around this problem - willing to help debug however needed.

**Comment by cswanson2** [comment]
I looked through the sync code... there are lots of variables that look like LOG_STDOUT and DEBUG_LEVEL_MAX and such... maybe even a "log file" versus a "logger". If someone can tell me how to turn them on I can run on CLI and get the logs that way

**Comment by ibamadd** [comment]
@cswanson2 - you figure this out?

**Comment by vtmateos** [comment]
Hi @ibamadd ,

If you are experiencing connectivity issues and in order to check what is happening, could you please generate a log file?
In order to do so on macOS: 
Please launch your sync client from the beginning with CMD+Shift (OS X) or CTRL+Shift (Win) pressed and double click the client. Here you are detailed steps to do it. If you have any problem during this process please contact our support team at support@mega.nz

1.- Close MEGAsync.
2.- Reinstall it again from here: https://mega.nz/#sync
3.- Go to the path of your MEGAsync installation and locate the MEGAsync executable file. For OS X system go to /Applications, for Win systems go to your desktop shortcut or to C:\Users\<Username>\AppData\Local\MEGAsync.
4.- Launch MEGAsync pressing CMD+Shift (OS X) or CTRL+Shift (Win) double click the client icon. For Linux users, just open a terminal and execute the command `megasync --debug`
5.- MEGAsync will start in a debugging mode. From this moment a file named MEGAsync.log will be generated at your Desktop.
6.- Reproduce the issue and provide detailed operation you perform.
7.- To disable the generation of log messages, just close the client and open it in a usual way.

Since the log could contain sensitive data (mainly file names) it would be better if you
send it to support@mega.nz along with the the URL of this issue on GitHub.

Thank you.

**Comment by cswanson2** [comment]
Not at all - Megasync told me to go pound sand - even though I 
reproduced this on 4 diff macs, and was completely willing to help them 
debug it, etc.

I gave up and moved to a cloud system that knows how to support it's 
customers properly.

**Comment by ibamadd** [comment]
I'm on Yosemite. DId you try the above? I'm gonna give it a whirl and report back

**Comment by vtmateos** [comment]
Hi @ibamadd ,

First time you launch MEGAsync, it will prompt you the screen you mention asking for username and password of your system account (macOS), necessary to access system notifications for sync tasks through fsevents.

In any case, you should NOT enter your MEGA credentials at this step, you will have to provide them through the login screen of the program later.

@cswanson2 
I am sorry you have issues trying to use MEGAsync. MEGAsync for macOS systems is supported from Snow Leopard 10.6 to latest one High Sierra 10.13. 
Here you are help centre of MEGAsync 
https://mega.nz/help/client/megasync/getting-started

Hope it helps.

Kind regards.

**Comment by cswanson2** [comment]
I got it working.. no idea how... did exactly the same as before and it worked... not on High Sierra, one right before that

**Comment by bjargal** [comment]
Mega.nz team you've gotta be kidding me. Why not put an explicit message that YOUR MAC USER NAME AND PASS ARE REQUIRED AT THIS STAGE. F*ck! I couldn't use the desktop client for one year, motherf*cking motherf*ckers!

**Comment by garenyondem** [comment]
> Mega.nz team you've gotta be kidding me. Why not put an explicit message that YOUR MAC USER NAME AND PASS ARE REQUIRED AT THIS STAGE. F_ck! I couldn't use the desktop client for one year, motherf_cking motherf*ckers!

no way! Started using mac after one year. It feels like I have been discovering this secret again and again.
