### ISSUE TITLE
Problem with tick the checkbox in sync

### ISSUE THREAD

**Issue by doxdank** [meganz/MEGAsync#459]
I try to tick the checkbox and apply, but it unchecks itself and does not sync my files. 
Link for a video on Youtube below:
[https://youtu.be/JXhPMozJK-g ](url)

**Comment by mattw-mega** [comment]
There must be something wrong with the paths you are trying to sync (and we should have better error reporting for that).   You can check you log file at C:\Users\<you>\AppData\Local\Mega Limited\MEGAsync\logs\MEGAsync.log  to see what the problem is - just recreate the issue and then open the file and look at the end of it.  thanks

**Comment by doxdank** [comment]
06/18-22:16:32.257323 11348 INFO Request (ADD_SYNC) starting [megaapi_impl.cpp:15623]
06/18-22:16:32.258170 11348 DBG  Filesystem type: NTFS
06/18-22:16:32.258252 11348 DBG  Excluded: \\?\C:\Users\doxda\OneDrive - UNIVALI   Attributes: 1073 [fs.cpp:552]
06/18-22:16:32.258257 11348 ERR  Error starting request: -9 [megaapi_impl.cpp:21785]
06/18-22:16:32.258260 11348 WARN Request (ADD_SYNC) finished with error: Not found [megaapi_impl.cpp:15651]
06/18-22:16:32.397909 11348 INFO Request (USE_HTTPS_ONLY) starting [megaapi_impl.cpp:15623]
06/18-22:16:32.397924 11348 INFO Request (USE_HTTPS_ONLY) finished [megaapi_impl.cpp:15655]
06/18-22:16:32.403126 13056 ERR  Error adding sync [:-1]

**Comment by doxdank** [comment]
I had this synced folder before. This problem started today.

**Comment by mattw-mega** [comment]
MEGAsync can't sync that folder because it has the FILE_ATTRIBUTE_REPARSE_POINT tag (so it's not really a folder, but it's a reference to some other folder or file system).  Did you change that recently?  (Or, since you have OneDrive in the name there, perhaps it has modified your folder be a reaparse point instead?)    You can set MEGAsync to sync that referenced folder instead.  cheers

**Comment by doxdank** [comment]
Thank you
!
