### ISSUE TITLE
Linux permissions and interaction with rsync

### ISSUE THREAD

**Issue by diegobersanetti** [meganz/MEGAsync#46]
I often use rsync to synchronize a remote server with my local machine; they both run Linux with ext4 filesystems, but with different users/permissions. The synched folder is inside MEGAsync's tree, and is synchronized online. However, everytime I pull the changes from the remote server to my local machine, MEGAsync downloads back the old copies and overwrites them, so the next time I use rsync it complains that the files are differents and syncs them again, and the cycle repeats... This happens only when the file content is not changed, otherwise everything works as expected.

**Comment by pohutukawa** [comment]
I remember that. I've also mentioned to the dev team internally that Linux file attributes are ignored. But it was not important at the time. I guess it still isn't important (enough) ...

**Comment by javiserrano** [comment]
@diegobersanetti MEGAsync uses the a CRC of file contents, the size and the modification time to detect changes. Maybe rsync is changing the modification time of files and that causes the problem. Have you tried (or are already using) the flag `-t` to force `rsync` to keep the modification time of files?

**Comment by pohutukawa** [comment]
That still won't solve the problem with file attributes such as permissions. Though, as far as it's about file contents and avoiding a cyclic re-sync, that works.

**Comment by javiserrano** [comment]
Yes, the synchronization of permissions is still not supported by our SDK

**Comment by diegobersanetti** [comment]
@javiserrano I have tried using the '-t' rsync flag, but MEGAsync's behaviour is the same in both cases.

Since MEGAsync officially supports Linux, it would be nice if it would support very basic Linux functionality, like permissions.

**Comment by javiserrano** [comment]
@diegobersanetti I'm sorry to read that. We will need some debugging info to know what's exactly the problem.

Could you tell me all options used in your `rsync` command?
That way we could check that exact case by ourselves.

It would also be very useful to have a log reproducing the problem.
To get it, please close MEGAsync, and run it in a terminal in this way:

`megasync --debug > log.txt`

In that moment, please reproduce the problem. The log file should show why those files are being synchronized again.

Since the log could contain sensitive data (mainly file names) it would be better if you send it to support@mega.nz along with the name of one of the files that shouldn't have been synced and the URL of this issue on GitHub. That way, the report should reach the developmenent team fast and we would carefully review it to fix any possible bug.

Thanks!

**Comment by diegobersanetti** [comment]
Hello, I'm sorry for the delay! I sent an email as per your instructions, with the requested informations/logfiles.

Cheers,

Diego

**Comment by polmr** [comment]
This has already been clarified long ago. If further info required, don't hesitate to open a new issue.

**Comment by averyfreeman** [comment]
Design your rsync script so that the mega folder is omitted from transfer (?)
