### ISSUE TITLE
In which case will the client receive MegaError::API_ETOOMANY?

### ISSUE THREAD

**Issue by richul** [meganz/MEGAsync#48]
Hi, in which case will the client receive MegaError::API_ETOOMANY?
thanks.

**Comment by javiserrano** [comment]
Hi,

It's received when the server has to send to the client too many updates over the local cached state. In that case, instead of getting modifications from the server and apply them over the local state, the client requests to the server the current state of the account (using a `fetchnodes` request).

This could happen, for example, if you start MEGAsync and log in. Then, you keep it closed for half a year, during that time you make a lot of changes in your account using other clients (web, mobile, etc.) and finally you try to start MEGAsync again.

**Comment by richul** [comment]
Hi,
Thank you for your comment. 
The warning message of MegaError::API_ETOOMANY in SetupWizard.cpp is:
...
 else if (error->getErrorCode() == MegaError::API_ETOOMANY)
            {
                QMessageBox::warning(this, tr("Error"),
                                     tr("You have attempted to log in too many times.[BR]Please wait until %1 and try again.")
                                     .replace(QString::fromUtf8("[BR]"), QString::fromUtf8("\n"))
                                     .arg(QTime::currentTime().addSecs(3600).toString(QString::fromUtf8("hh:mm")))
                                     , QMessageBox::Ok);
            }
...

The meaning of the message doesn't look like the above comment.  
It will make the user to wait for a while other than to request to the server the current state of the account.
How will the client trigger the error and have to wait for a while made me puzzled.

**Comment by javiserrano** [comment]
Oops, you are right. Previously, the usage of `API_ETOOMANY` was only related to the issue above and when the servers are receiving too many requests in a short time from the same client, but currently it can be received also as a response for the login request. 

In that case, it means that the user has tried to log in without success too many times in a short time and that, for that reason, next login attempts will be blocked during one hour.

Currently, I think that the server consider that 10 are too many failed attempts, but that's controlled on the server side and can change.

This error should be only received after too many **failed** login attempts, so it shouldn't be received when you log in with your correct user and password. It's a protection to prevent bruteforce attacks.

**Comment by richul** [comment]
Got it.
Thank you for your kindly comments.
