### ISSUE TITLE
How to uninstall MEGAsync

### ISSUE THREAD

**Issue by kevinmickey** [meganz/MEGAsync#54]
How do I completely uninstall MEGAsync?  I have it installed on a mac. Thanks!

**Comment by polmr** [comment]
Uninstall it as you'd do with any mac app: Open Applications on Finder and drag and drop it to the trash in your dock. You'd probably want to close session before that: Open Megasync->Preferences->Account->Logout. Other preferences such as sync folders or excluded files will remain stored (encrypted). If you also want to delete those, they are stored (at least in OS X El Capitan) at: 
"/Users/UserName/Library/Application Support/Mega Limited/MEGAsync"

**Comment by kevinmickey** [comment]
Thanks!

**Comment by ballII** [comment]
When I tried to drag and drop MEGAsync to the trash after I logged out, an error message popped out:

"The item "MEGAsync" can't be moved to the Trash because some of its plugins are in use."

I checked Activity Monitor and find a plugin called "MEGA Finder Sync", which could not be stopped by simply clicking the "cross" icon ("Force the process to quit"). How can I stop the plugin?

**Comment by vtmateos** [comment]
Hi @ballII , 

_"MEGA Finder Sync"_ is the Finder extension responsible of show status badges and contextual menus. You need to disable from the system preferences in order to remove it. Please, try this:
Go to System preferences -> Extensions -> Finder. Then uncheck "MEGA Finder Sync". Then remove MEGAsync or drag&drop to the trash.

Hope it helps.

**Comment by ballII** [comment]
@vtmateos , thank you. It works.

**Comment by valtism** [comment]
This doesn't work for me in a specific instance. When I have started the app it prompts me to log in or create an account. If I exit the setup wizard, then try to delete the app, I get @ballII's error. This is despite having the finder extension unchecked, and toggling it does not help. Relaunching finder also does not help.

**Comment by vtmateos** [comment]
Hi,

This error is produced because you have MEGAsync process or extension already running in your system. Please open Activity monitor and search for "mega" in order to check if there is any of our processes running. Check it out this screenshot, you have to be sure that none of them are active.
![captura de pantalla 2018-03-05 a las 10 03 48](https://user-images.githubusercontent.com/7125573/36966374-e4514afa-205c-11e8-91bd-862b7ee4d096.png)

**Comment by srsandy** [comment]
@vtmateos Open Finder -> Applications -> Right click MEGAsync ->Show Package Contents 
A new Finder window will pop up. Delete the **Content** folder. Then drag and drop MEGAsync to the trash.

**Comment by fibie1** [comment]
hello,
Thank you very much. 
Thanks to you, I was able to uninstall the software 
it feels good :)

**Comment by norm320** [comment]
J'ai fait la procédure décrite par fibie1, afin que l'application disparaisse de la liste des applications, en plus de faire la procédure décrite, il faut redémarrer.

**Comment by martin-martin** [comment]
I have deleted MegaSync on MacOS, but my Console is still showing a process called `MEGAShellExtFinder` on every startup:

```
default	14:35:33.651312+0300	MEGAShellExtFinder	ERROR - Unable to stablish connection with server
```

How can I get rid of this process?

**Comment by vtmateos** [comment]
@martin-martin , You should disable Finder sync extension of MEGAsync first. Go to System preferences -> Extensions -> Finder -> Uncheck MEGAsync finder extension. Afterwards, delete MEGAsync from /Applications.

Hope it helps.
