### ISSUE TITLE
MEGAsync delay fedora from shutdown about 2 minutes

### ISSUE THREAD

**Issue by shoukunhuai** [meganz/MEGAsync#579]
I use MEGAsync on fedora 33/34 workstation, when i shutdown, MEGAsync will ask if i want to quit, and i choose yes.
The shutdown process was delayed 2 minutes, in console
`
a stop job is running for user manager
`

If i quit MEGAsync before shutdown, the process is quit quick.

Same thing happened to Ubuntu sometimes.

**Comment by polmr** [comment]
Hi there, this happens because restarting is pending the acceptance of the closure dialog of MEGAsync's main UI.
In Fedora 33/34, MEGAsync is run as a foreground app when starting, given the absence of a system tray to let you interact with it.
You can avoid that by launching MEGAsync with START_MEGASYNC_IN_BACKGROUND=1:
In order to do so, edit `~/.config/autostart/megasync.desktop`
Replacing:
```
Exec=megasync
```
with
```
Exec=sh -c "START_MEGASYNC_IN_BACKGROUND=1 megasync"
```

**Comment by shoukunhuai** [comment]
Thanks, it works. I will close this issue
