### ISSUE TITLE
MEGASync client does not scale on HIDPI displays Linux Mint 18.1 cinnamon.

### ISSUE THREAD

**Issue by lubo08** [meganz/MEGAsync#58]
In Linux (Mint 18.1 Cinnamon in my case), the MEGASync client does not scale on HIDPI displays causing everything to appear really tiny. tray icon is also too small. Linux mint setup General -> double (HI-DPI).

Megasync client version 2.9.10 (2c928).

**Comment by polmr** [comment]
I'm afraid we are not currently supporting HIDPI for linux Mint 18.1. This is due to the fact that mint 18 features QT 5 < 5.6. We've found some issues with the tray icon in such QT version. Hence, we are using qt4 for linux mint package. HIDPI support is only available for distributions with qt5 >=5.6 (e.g: Ubuntu 16.10). However, you can try this package I have just created that will install in your system.
[megasyncmint18qt5.zip](https://github.com/meganz/MEGAsync/files/682057/megasyncmint18qt5.zip)

And start megasync (if already opened, close it before) with:

`QT_DEVICE_PIXEL_RATIO=2 megasync`

Note: you can use another value other than 2 to fit your needs.
Note 2: if your tray icon dissapears, remember you can always re-launch megasync and it will show up the main UI in case it is already open.

**Comment by emseel** [comment]
@polmr Works great, thanks. 
![mintmega](https://cloud.githubusercontent.com/assets/16466770/25421218/694cf8fe-2a21-11e7-87b5-8d92c2ecc20c.png)

**Comment by insign** [comment]
@polmr worked great!
