### ISSUE TITLE
Possible memory leak

### ISSUE THREAD

**Issue by Dsibe** [meganz/MEGAsync#595]
Hello!
Recently I updated MEGAsync to version 4.5.1 from 4.5.0, and after that, an issue appeared.
When I start the MEGAsync, the RAM usage starts to grow quickly.
After a couple of minutes running MEGAsync (and sometimes completing all the syncs), it uses ~10GB of RAM.
It always happens, even if everything is already synced.
I attach a screenshot, where you can see it by yourself.
Is this behavior considered normal, or it's an issue?

Some information:
  Windows 10 Home (build 17763)
  Laptop Asus x510uar
  RAM: 16GB
  CPU: Intel i5-8250u
  Used storage in cloud: 22.2/50GB

Please let me know if you need any other information.
Thank you.

![изображение](https://user-images.githubusercontent.com/42495727/122672944-d9126500-d1d6-11eb-8d17-35680894d2a1.png)

**Comment by vtmateos** [comment]
Thanks for the report and information. We are currently working on that. Apologies and stay tuned for new MEGAsync updates.

**Comment by EmileCalixte** [comment]
Hi,

Same for me, with two computers (Win 10 pro, 16 and 32 GB RAM): 
![image](https://user-images.githubusercontent.com/26703184/123216676-17a36a80-d4ca-11eb-8f4f-c471cc3a4438.png)
![image](https://user-images.githubusercontent.com/26703184/123216779-2f7aee80-d4ca-11eb-9bec-a81f29089556.png)

Total files stored on my MEGA cloud are 139 GB, with 78.5 GB synced.

The application seems to be stuck in its 'Analysis' phase.
![image](https://user-images.githubusercontent.com/26703184/123216496-e4f97200-d4c9-11eb-90ac-eb75312c051a.png)

If I don't kill the process, it ends up taking up all available memory and swap and makes other applications crash.

Should we go back to 4.5.0 until the problem is solved?

**Comment by Dsibe** [comment]
> 
> 
> Thanks for the report and information. We are currently working on that. Apologies and stay tuned for new MEGAsync updates.

Great, thanks for the information.
Recently, I found out something interesting.
On my another PC (with the same Mega account and MEGASync version) this issue doesn't happen and MEGASync uses normal amount of RAM (350mb).

Some information about the PC:
  MEGASync 4.5.1 (same)
  Mega account - same
  32gb RAM
  AMD Ryzen 5 3600
  Windows 10 Pro
  GTX 1660 super
  
Thank you.

**Comment by vtmateos** [comment]
Hi,
We have prepared a new version of MEGAsync 4.5.2 (d19f6b1) which include some fixes for the memory issues detected. If you want to check this new version, you can get it through our website. Just reinstall with latest public installer. 
The roll out for the autoupdate will take place in the following days.

Thanks.

**Comment by EmileCalixte** [comment]
> Hi,
> We have prepared a new version of MEGAsync 4.5.2 (d19f6b1) which include some fixes for the memory issues detected. If you want to check this new version, you can get it through our website. Just reinstall with latest public installer.
> The roll out for the autoupdate will take place in the following days.
> 
> Thanks.

Hi,

Just downloaded and installed it on my main device, seems to work well now. Thanks!

**Comment by Dsibe** [comment]
> 
> 
> Hi,
> We have prepared a new version of MEGAsync 4.5.2 (d19f6b1) which include some fixes for the memory issues detected. If you want to check this new version, you can get it through our website. Just reinstall with latest public installer.
> The roll out for the autoupdate will take place in the following days.
> 
> Thanks.

Thank you very much! Everything works well!
