### ISSUE TITLE
Permission to package the software for FreeBSD

### ISSUE THREAD

**Issue by clausecker** [meganz/MEGAsync#606]
I would like to provide a FreeBSD package (port) for this software, but unfortunately the license does not permit this.

Please give permission to compile and run the software from the sources given here and to apply patches necessary for compiling the program on FreeBSD and other operating systems.  If possible, also give permission to distribute binary packages for FreeBSD based on these sources.

If the former permission is not given, no FreeBSD package can be created.  If the latter permission is not given, a FreeBSD port can be created, but users will have to compile it themselves (making the port less accessible to inexperienced users).

**Comment by sakethv-mega** [comment]
Hello there, we can confirm that you are free to port and distribute binaries for freeBSD and other operating systems using the resources we provide and we are totally fine with it. Thank you for helping MEGA reach a more diverse user base.

**Comment by wasfourie** [comment]
@clausecker  Has the FreeBSD port been made public available elsewhere that it be obtained?

**Comment by clausecker** [comment]
@wasfourie I haven't started yet.  I was busy with other work.

**Comment by Leedehai** [comment]
> Hello there, we can confirm that you are free to port and distribute binaries for freeBSD and other operating systems using the resources we provide and we are totally fine with it. Thank you for helping MEGA reach a more diverse user base.

Hi @sakethv-mega -  it appears your comment is different from the current LICENSE.md, which says "we grant you... licence[sic] to access and use the code solely for review purposes" and "...you are not entitled to use or do anything with the code for any commercial or other purpose, other than review and commentary on it", where "review" is defined as "access, analyse, test and otherwise review the code as a reference, for the sole purpose of analysing it for defects".

(Related: https://github.com/meganz/MEGAsync/issues/583)

Maybe update the license wording please?
