### ISSUE TITLE
MEGAsync uploads files from USB drive again after switching computers

### ISSUE THREAD

**Issue by Guardian1987** [meganz/MEGAsync#633]
Hi MEGA team,

I used a raspberrypi with an exfat formatted harddrive to store files that were synced with megasync.
I switched from a raspberrypi to a mini PC, attached the same harddrive with the fully in sync data and now megasync thinks it has to reupload the entire content of that harddrive.

Sizes and MTime are unchanged as it is the same file on the same harddrive. Any idea why this occurs or what kind of data I can provide to stop this behaviour?

I'm not super keen on reuploading the remaining 6849 files on my hard drive:

![image](https://user-images.githubusercontent.com/53516713/139286422-83d686e2-a689-4f6f-b36d-c88e21080568.png)

Best regards

**Comment by mattw-mega** [comment]
The difference between mtimes (LNmtime (local) vs Nmtime (cloud)) is 3600 seconds, exactly one hour.   Somehow, the drive in its new location is reporting a different mtime - this could be because it's formatted FAT which only records local time and not UTC, and you've gone through daylight savings (and can vary depending on platform, driver, etc)?  Or you know your situation better, how else could the exactly 1 hour difference occur?   Anyway, we don't have a tool to do that but perhaps something more generic could move the on-disk mtimes back one hour.

**Comment by mattw-mega** [comment]
Or it could have been due to an incorrectly set clock (perhaps with a compensating time zone setting so it seemed correct) on one device or the other.

**Comment by Guardian1987** [comment]
Thanks for the feedback. If I switch hard drives at another point I will try a different format.
