### ISSUE TITLE
MEGAsync Portable

### ISSUE THREAD

**Issue by Himusaki** [meganz/MEGAsync#642]
Hello Team,
Can i get a reply on Portable version 

i dont want to download free from google and ruin my security

But can you guys create and publish any portable version for mega sync ?
That would be very helpful

I hv to keep moving from one VM to another VM 
its painful to keep logging into each one and wait for files to load.

Thanks for the security.

**Comment by sakethv-mega** [comment]
Hello,

You can use MEGAsync from an USB stick just copying the content of the path "C:\Users<username>\AppData\Local\MEGAsync" generated during a normal installation. 

Please take into account that the current executable isn't really suited to being copied onto a USB since all the persistent sync data is still kept on the PC rather than on the USB.   
If you can install it on the PC and use it from there, that would be preferred.

However, it should work as long as:
- The USB format is NTFS
- You sync that USB on a single machine, not on multiple computers as MEGAsync client synchronises local paths with your MEGA account paths. If you are on a different computer, the local path probably won't be the same.
- You only start MEGAsync after the USB is plugged in (and has been given the same drive letter as before)
- You exit MEGAsync before unplugging the USB (ie. only have MEGAsync running when the USB is present)

If you do not follow the above recommendations, that could cause synchronisation problems such as cloud-deleted files being re-uploaded.

Please, take into account that MEGAsync configuration saved on the PC won't travel with the USB, so using it with MEGAsync on another PC will also cause issues, therefore it's best to only sync it on one PC.

**Comment by Himusaki** [comment]
> Hello,
> 
> You can use MEGAsync from an USB stick just copying the content of the path "C:\Users\AppData\Local\MEGAsync" generated during a normal installation.
> 
> Please take into account that the current executable isn't really suited to being copied onto a USB since all the persistent sync data is still kept on the PC rather than on the USB. If you can install it on the PC and use it from there, that would be preferred.
> 
> However, it should work as long as:
> 
> * The USB format is NTFS
> * You sync that USB on a single machine, not on multiple computers as MEGAsync client synchronises local paths with your MEGA account paths. If you are on a different computer, the local path probably won't be the same.
> * You only start MEGAsync after the USB is plugged in (and has been given the same drive letter as before)
> * You exit MEGAsync before unplugging the USB (ie. only have MEGAsync running when the USB is present)
> 
> If you do not follow the above recommendations, that could cause synchronisation problems such as cloud-deleted files being re-uploaded.
> 
> Please, take into account that MEGAsync configuration saved on the PC won't travel with the USB, so using it with MEGAsync on another PC will also cause issues, therefore it's best to only sync it on one PC.

Thanks.

**Comment by flesti** [comment]
Still doesn't work. With every step and detail taken care of and the local appdata copy at place. Still asks for login and new setup at every new pc is attempted to run from a usb stick. 

I am guessing megasync is secretly putting something deep in to windows system on install or run.
