### ISSUE TITLE
Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by jignac05** [meganz/MEGAsync#649]
I can't run megasync desktop app on Ubuntu 21.10. When I try to run command "megasync" in terminal, it writes me "Segmentation fault (core dumped)".

**Comment by sakethv-mega** [comment]
Hello,

Can you please paste the output here so that we can check? Thank you.

**Comment by jignac05** [comment]
![Screenshot from 2021-11-30 17-36-20](https://user-images.githubusercontent.com/85819995/144089216-90f56c18-4a55-40e3-82f6-837d7221a9d5.png)

**Comment by polmr** [comment]
Hi @jignac05 
MEGAsync is crashing for some reason.
We are about to release a new version that may content a the fix for that, but in order to determine what is the cause, we can gather some information if we examine what are all the threads doing in the moment of the crash. In order to do that, we'd need you to run megasync with a debugger (gdb). But first, you need to have debug symbols installed:
To install symbols, execute in a console:
```
sudo apt install megasync-dbg
```
To run megasync with gdb (If you don't have it installed, do `sudo apt install gdb`):
```
gdb megasync
```
in the console enter "r" + Intro
and whenever it crashes:
```
thread apply all bt
```
(it will ask you to type enter to show all the pages)
Then, give us the outputs of all those threads.

Also, a log of what was megasync doing at the moment would also be useful.
You can get it by executing megasync with:
```
megasync --debug > logfile.txt
```
Notice, that file may contain sensitive information, you may not want to post it here. Please, write to support@mega.nz with it, and reference this issue so that that can reach our development team.
Thanks for your collaboration @jignac05

**Comment by jignac05** [comment]
E-mail was sent.
