### ISSUE TITLE
MEGAsync seg faults on Ubuntu

### ISSUE THREAD

**Issue by Sush-ruta** [meganz/MEGAsync#682]
Hello,
I have been using MEGAsync for years without problem. But suddenly I noticed that the tray icon was missing, so I tried opening the app, but it won't open. Starting it from terminal gives the following output:
```
megasync
Error unsetting QT_QPA_PLATFORMTHEME vble
Segmentation fault (core dumped)
```
Looking at [another issue](https://github.com/meganz/MEGAsync/issues/275), I tried `DO_NOT_UNSET_QT_QPA_PLATFORMTHEME=1 DO_NOT_SET_DESKTOP_SETTINGS_UNAWARE=1 megasync`. It doesn't solve the issue.
```
DO_NOT_UNSET_QT_QPA_PLATFORMTHEME=1 DO_NOT_SET_DESKTOP_SETTINGS_UNAWARE=1 megasync
Segmentation fault (core dumped)
```
[Screenshot of terminal outputs](https://imgur.com/a/c03k10l) for reference.
I have tried reinstalling MEGAsync, it doesn't solve the problem. I am at my wits' end. Any help is greatly appreciated.

OS: Ubuntu 21.10
MEGAsync version: 4.6.3

**Comment by polmr** [comment]
Hi @Sush-ruta , perhaps this may help youL https://github.com/meganz/MEGAcmd/issues/608
In any case, MEGAsync is crashing for some reason.
In order to determine what is the cause, we can gather some information if we examine what are all the threads doing in the moment of the crash. In order to do that, we'd need you to run megasync with a debugger (gdb). But first, you need to have debug symbols installed:
To install symbols, execute in a console:
```
sudo apt install megasync-dbg
```
To run megasync with gdb (If you don't have it installed, do `sudo apt install gdb`):
```
gdb megasync
```
in the console enter "r" + Intro
and whenever it crashes:
```
thread apply all bt
```
(it will ask you to type enter to show all the pages)
Then, give us the outputs of all those threads.

Also, a log of what was megasync doing at the moment would also be useful.
You can get it by executing megasync with:
```
megasync --debug > logfile.txt
```
Notice, that file may contain sensitive information, you may not want to post it here. Please, write to support@mega.nz with it, and reference this issue so that that can reach our development team.
Thanks for your collaboration @Sush-ruta

**Comment by Sush-ruta** [comment]
Hi @polmr the solution mentioned [here](https://github.com/meganz/MEGAcmd/issues/608) worked for me. MEGAsync now runs as usual. Thank you for the help! :)

**Comment by InfoTriqs** [comment]
### gdb megasync
GNU gdb (Debian 10.1-1.7) 10.1.90.20210103-git
Copyright (C) 2021 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<https://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from megasync...
Reading symbols from /usr/lib/debug/.build-id/ea/de0f0fce2d51d8dec0b07785346f0c878d8cd1.debug...
(gdb) thread apply all bt
(gdb) r
Starting program: /usr/bin/megasync 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[Detaching after fork from child process 40349]
Error for "xrdb -query" command: "xrdb: Can't open display ''\n"
qt.qpa.xcb: could not connect to display 
QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-guilherme'

Program received signal SIGSEGV, Segmentation fault.
0x00007ffff142a60c in QXcbIntegration::initialize() ()
   from /lib/x86_64-linux-gnu/libQt5XcbQpa.so.5
(gdb) thread apply all bt

Thread 1 (Thread 0x7ffff18b1e80 (LWP 40345) "megasync"):
#0  0x00007ffff142a60c in QXcbIntegration::initialize() () at /lib/x86_64-linux-gnu/libQt5XcbQpa.so.5
#1  0x00007ffff158ac50 in deepin_platform_plugin::DPlatformIntegration::initialize() () at /usr/lib/x86_64-linux-gnu/qt5/plugins/platforms/libdxcb.so
#2  0x00007ffff5f02d79 in QGuiApplicationPrivate::eventDispatcherReady() () at /lib/x86_64-linux-gnu/libQt5Gui.so.5
#3  0x00007ffff5928846 in QCoreApplicationPrivate::init() () at /lib/x86_64-linux-gnu/libQt5Core.so.5
#4  0x00007ffff5f05c9f in QGuiApplicationPrivate::init() () at /lib/x86_64-linux-gnu/libQt5Gui.so.5
#5  0x00007ffff5f06bd4 in QGuiApplication::QGuiApplication(int&, char**, int) () at /lib/x86_64-linux-gnu/libQt5Gui.so.5
#6  0x0000555555a7a16c in createScreensInfo(OsType, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) (osType=OsType::LINUX, desktopName="") at ScaleFactorManager.cpp:67
#7  0x0000555555a7a5b9 in ScaleFactorManager::ScaleFactorManager(OsType) (this=0x7fffffffe000, osType=OsType::LINUX) at ScaleFactorManager.cpp:98
#8  0x00005555556fcf7b in main(int, char**) (argc=<optimized out>, argv=0x7fffffffe6e8) at main.cpp:366
(gdb)
