### ISSUE TITLE
Can't build v4.6.3 on x86 Linux

### ISSUE THREAD

**Issue by DurhamDecLab** [meganz/MEGAsync#689]
Trying to build v4.6.3 on 32-bit MX Linux (was able to successfully build v4.4.0). First issue was missing src/archives despite having:
libmediainfo-dev is already the newest version (20.09+dfsg-2).
libzen-dev is already the newest version (0.4.38-1).
I've worked around by finding the required freeimage / zenlib / libmedia sources and renaming them. 

On ./configure I get: 
checking for libcryptopp... checking cryptopp/cryptlib.h usability... yes
checking cryptopp/cryptlib.h presence... yes
checking for cryptopp/cryptlib.h... yes
checking for main in -lcryptopp... no
configure: error: Could not find libcryptopp

I've also tried ./configure -q

Build requirements should be satisfied, libcrypto++-dev is already the newest version (8.4.0-1) . Can you advise? Many thanks.

**Comment by aabellagm** [comment]
Hi @DurhamDecLab 

Please check if you have installed `libudev-dev` in your system, it could be the root cause of your issue.

Anyway, my recommendation is to get the current code in master branch (4.6.5) and make a small fix in the configure script (it will be fixed in the next version):
Edit `src/configure` script and remove the `-f` in line 76.
`libudev-dev` package is still need if you decide to build the 4.6.5 version.

If you still have problems, you can review the config.log file located at src/MEGASync/mega/config.log, or share a link here to it so we can investigate it to help you.

Thanks!

**Comment by DurhamDecLab** [comment]
Hi @aabellagm ,
Many thanks for the response. Changing line 76 allows configure to bring down the extra packages to archive, and adding libudev-dev as well allowed it to build. Much appreciated.
