### ISSUE TITLE
[4.6.6] Upload Speed Spikes and Fluctuates

### ISSUE THREAD

**Issue by hl2guide** [meganz/MEGAsync#699]
The upload speed while uploading files used to be rock solid and fast but since updating to version 4.6.6 (Windows) it now fluctuates, spikes and is slower overall.

**Comment by angelds-mega** [comment]
Hello,

On occasion, you may experience slow uploads or downloads. Slower speeds are never due to MEGA as we do not artificially limit your throughput (your account status makes no difference).

The following factors determine how fast you can upload or download:
1. The true bitrate of your Internet connection (which is often slower for uploads than for downloads). Note that to sustain 1 MB/s (megabytes/second), your connection speed must be approx. 10 Mb/s (megabits/second). 
Please don’t confuse MB/s and Mb/s: MEGA reports throughput in MB/s while your Internet Service Provider (ISP) uses Mb/s.

2. Packet loss on the network path from you to us or vice versa. This can happen due to bottlenecks in the network of an upstream carrier or, more commonly, due to overloaded peerings between upstream carriers.

3. The size of your Transmission Control Protocol (TCP) send and receive buffers (at our end, buffers can grow very large if needed). TCP works with the Internet Protocol (IP), which defines how computers send packets of data to each other. Older operating systems use very small buffers.

4. The total time it takes for a packet to travel between us, in both directions (“round-trip time”). The longer, the slower at the same buffer size.

5. Your ISP intercepting your HTTP traffic and caching it on slow or overloaded servers.

Tips to improve your upload performance:

Desktop app

Navigate to the “Network” tab in Settings/Preferences and click on “Change Settings…” button in the rate limit row.
– Ensure the check box “Don’t use HTTP” is enabled as your ISP might be caching HTTP connections to MEGA’s servers and this will avoid it (by using cache-proof HTTPS instead, at the expense of additional CPU load).
– Increase the number of connections per uploads to 6 if you are uploading lots of small files.
– Set the “Upload rate limit” to “Auto”. If you are already using that setting, change to “No limit”.

If any of the tips above has not helped we suggest to enquire with your ISP and get them to check all connection points between you and the MEGA servers. 

Keep in mind that your data might have to travel internationally. That means your ISP must have enough overseas bandwidth capacity available. This might be a problem during the peak hours of the day, which is when the American and European business days overlap (European afternoon/American morning).
