### ISSUE TITLE
Sync hangs when changing small files often

### ISSUE THREAD

**Issue by sawft99** [meganz/MEGAsync#745]
I use [Obsidian](https://obsidian.md) to make some basic text files with Markdown. I keep my vault, just a folder with all of the individual files, in my Mega folder. Obsidian writes changes to the file as you change them on the fly. So if I'm continually typing and switching between several pages as well, every few seconds it changes and Mega is going to keep trying to upload it of course. I am only using maybe 2 or 3 files at once max. After some time with these many fast changes, again on small text files, Mega seems to just hang on syncing. It's not just those text files that hang either, it causes all syncing to hang. If I stop doing anything for maybe 5 minutes it'll "catch up" but the issue will occur again shortly after as I keep working that way.

**Comment by jx-mega** [comment]
Hello,

If you are editing some synced files, it may occur that when you save your changes the updated file won't sync with the cloud or as you said "hang on syncing".

This could be a problem related to an exclusive lock of the program against the file, for example, Word documents on Windows that don't let to sync the file until you close Microsoft Word.
Or during the phase of scanning and analyzing local and remote files, the transfer is waiting either on file attributes, or the final putnodes.

Please enable desktop notifications: go to Settings -> Notifications - enable "System notifications" to see if the Desktop app shows any informative message.

And please try the following when the issue occurs again:

1. Please make sure that you have installed the latest version of the Desktop app. 
Please log out of your account (go to the Desktop app interface -> Preferences -> Account -> Logout) and then reinstall the Desktop app from this link: https://mega.nz/desktop (please DO NOT un-install anything, simply install again).

2. From your Desktop app, go to Settings -> General -> Force a full scan
visit the MEGA website (https://mega.nz), go to Menu -> click "Reload your account" while holding the keyboard key <b>Ctrl</b>

If you still can reproduce the issue, we suggest you send us an email to support@mega.nz from your MEGA account email address so that we can have a better look into your account status.

**Comment by sawft99** [comment]
Fixed in #770
