### ISSUE TITLE
Files that start with a dot (.) do not upload

### ISSUE THREAD

**Issue by hl2guide** [meganz/MEGAsync#748]
Files that start with a dot (.) do not upload and are ignored by the app.

e.g. `.vscode.rar`

**Comment by cgbeutler** [comment]
Ran into this using Obsidian. This is really annoying for programs that use '.' folders to store settings that should be backed-up (like obsidian md, who's settings folder must start with a dot.)

It'd be nice to have a way to make exceptions to blacklist rules, but since this 'bug' has been reported twice and just closed unceremoniously, here are some workarounds:
1. Add OS-directories to the blacklist that use a '.' prefix. Here is a list pulled from common programmer lists (2023):
    ```
    ._*
    .AppleDB
    .AppleDesktop
    .AppleDouble
    .com.apple.timemachine.donotpresent
    .DocumentRevisions-V100
    .DS_Store
    .fseventsd
    .LSOverride
    .Spotlight-V100
    .TemporaryItems
    .Trashes
    .VolumeIcon.icns
    ```
2. Add any other '.' ignores for programs that may conflict.
3. Remove the '.*' black list rule

Another option is to make a symbolic link (that's name starts with '.') to a folder that doesn't get black-listed. This method, unfortunately, will require setup on each and every computer, but once done it should stay synced normally.
* Windows:
  1. Rename the settings folder to a valid upload name. Eg: '.obsidian' => '_obsidian'
  2. Open a terminal to the folder. Run `mklink /J .obsidian _obsidian`
  3. The '_obsidian' folder will now be backed-up. On a new computer you'll need to delete any '.obsidian' files and replace them with links, like in step 2.
