### ISSUE TITLE
Plex Cloud and Mega.nz, a future possibility?

### ISSUE THREAD

**Issue by chmercesmoreira** [meganz/MEGAsync#79]
Hello, yesterday was finally released officially Plex Cloud:
https://www.plex.tv/blog/plex-cloud-now-available-to-all-plex-pass-subscribers/
With Plex Cloud the users of Plex can use a cloud service as a remote repository for personal media, currently the cloud services available are: Dropbox, Google Drive and One Drive.
I want to know if mega.nz has a public API that could make it possible to the Plex developers to integrate their service with mega.nz servers, do you think it is going to happen?

**Comment by javiserrano** [comment]
Hi,

The API of MEGA servers is not documented and it's also not very useful for third-party developers because, due to end-to-end encryption, there is a significative complexity to implement a compatible client from the scratch (encryption, management of keys, RSA, AES, ...).

The recommended way to integrate any native app with MEGA is using our SDK:
https://github.com/meganz/sdk

Its high-level API (`megaapi.h`) is documented (please check the README) and we provide bindings for several languages, to create third-party apps with Java, Objective C++, C#, etc. All our public apps use our SDK to be 100% compatible.

**Comment by chmercesmoreira** [comment]
Ok, I'm going to send to the Plex support team a reference to this issue and ask them if there is any possibility to integrate both services in the future. If I receive any answer I'm going to post here, meanwhile I'm going to close this issue. Thank you for your answer.

**Comment by sam5558** [comment]
Any news about Mega Integration with Plex ?
