### ISSUE TITLE
paths not working in "Excluded file and folder names"

### ISSUE THREAD

**Issue by jakobrosenberg** [meganz/MEGAsync#9]
I have these runtime folders ``.meteor/local`` located in all my Meteor projects which I'd like MEGAsync to ignore.

However, adding ``.meteor/local`` to the "Excluded file and folder names" does nothing. Alternatively I can add just "local" to the list, but that would inadvertently have a global effect on all my files.

Any ideas?

**Comment by javiserrano** [comment]
The current exclusion list works with file or folder names only, not with entire paths.
So in this case, as you say, you would have to set `local`, `.meteor` (if you want to exclude everything in that folder), rename `local` to a different name that wouldn't cause side effects, or put `local` outside your synced folder an use a soft link instead (the current version of MEGAsync doesn't follow symlinks).

I'm sorry but I can't give you a better option in this moment. We plan to add more advanced exclusion features (including full paths and the usage of regular expressions) but they are not being actively developed now so they will take some months to be prioritized, implemented and released.

In the meantime, you could use `megasimplesync` that is one of the example console apps of our public SDK and uses exactly the same sync engine as MEGAsync. Using that app, you could easily modify it to fit your needs. If you decide to do so, we could assist you.

**Comment by jakobrosenberg** [comment]
Thanks for the quick reply @javiserrano 

I think I'll have to hold out for advanced exclusion features for now.

Have you considered compliance with .gitignore or a simple ignore file for each ignored folder?

**Comment by javiserrano** [comment]
Our fix option is something like a `.gitignore` per synced folder (not per ignored folder), but with a different name if the syntax is not `.gitignore` compatible (maybe something like .syncignore).

Also, there would be GUI tools to ease the addition and removal of files and folders in the exclusion list.

We already started the implementation months ago in this branch of the SDK:
https://github.com/meganz/sdk/commits/regexp

but it wasn't finished due to the higher priority of other tasks. When we can finally continue with that work, it's quite probable that we start from that code, so the implementation would be based on PCRE, and also the regular expressions that would be allowed:
http://www.pcre.org/

**Comment by jakobrosenberg** [comment]
Sounds amazing. Would you dare venture an estimate on when these features will be available?

**Comment by javiserrano** [comment]
It's very difficult to say in this moment. Maybe two-three months. The functionality could be ready and even publicly released earlier so power users could manually edit the configuration file, but I think that the GUI will probably take more time. Anyway, there are many variables involved that are out of my control so that estimation is not accurate at all, sorry :-/

**Comment by jakobrosenberg** [comment]
I'll stay optimistic. Thanks so much for your time @javiserrano.

**Comment by syrys** [comment]
@javiserrano 
is there any update to this? im looking for a sync solution that allows synced ignore list (similar to how gitignore file works in git). Looking at mega, hoping this would be the solution to my problem.

**Comment by nirg** [comment]
@javiserrano correct me if I'm wrong, but with the existing GUI, supporting path exclusion would only be a matter of using `fnmatch` instead of the WildcardMatch currently done in the SDK, wouldn't it?

(I'm having hard time compiling MEGASync on my mac in order to test such a change, I'm getting "Qt require C++11 support" error, which none of the solutions online resolved in my case)

**Comment by javiserrano** [comment]
Unfortunately there isn't any update about this issue yet. It has been postponed due to other priorities.

@nirg Indeed, exclusions are related to the usage of `WildcardMatch` in the SDK. Specifically, they are controlled by the return value of the callbacks `MegaApiImpl::sync_syncable`. `WildcardMatch` could be replaced with `fnmatch` but that wouldn't make exclusions work for full paths. To do it, it would be needed to match the whole paths instead of only file/folder names. The callback that filters local files already provides the path of files as a parameter, but the callback that filters remote files (Nodes) doesn't provide the path so it would be needed to construct it before using the matching function (if it's needed that exclusions work in both ways), and despite it's not very difficult, it's also not trivial.

About the problem to build MEGAsync, it could have different causes and solutions. It could be needed to add `-std=c++11` to compilation flags in MEGASync.pro (QMAKE_CXXFLAGS) or it could also be caused by the usage of the option `mmacosx-version-min` (Snow Leopard doesn't support C++11). An easy solution could be to use QT 5.3. I think that it shouldn't need C++11 at all.

**Comment by DrBones** [comment]
I'd second that :). 

Having a .gitignore like file and folder ignore capability would be great. Especially since no other large file sync provider offers anything like that and I would believe many developers with lots of identically named subfolders in different projects would appreciate that!

Thanks @javiserrano anyway for your helpful comments and open attitude 👍

**Comment by zimme** [comment]
I would really love to have an ignore file or at least a way to ignore a path. I'm in the same boat as the OP with that I have a lot of Meteor projects and I would love to have a way of ignoring `.meteor/local` folders.
