### ISSUE TITLE
Add option to remove Windows 10 quick access pin

### ISSUE THREAD

**Issue by shravan2x** [meganz/MEGAsync#91]
With the latest release of MEGASync v3.1.2, a MEGA shortcut is added to windows explorer.

![image](https://cloud.githubusercontent.com/assets/4096676/25963027/899ea92e-3645-11e7-9e2f-c8d33101052f.png)

Could an option be added to disable this?

**Comment by eric-tucker** [comment]
OMG this is terrible and the exact reason I stopped using Dropbox.

If I wanted quick access pins I'd drag and drop a link to the folder.

What's worse is if you are syncing multiple individual folders then every single sync is added as a non-removable pin.

Please read all of the forum posts on Dropbox of people hating this "feature".  Who on earth requested this?  Why did you add this with no way to disable it? 

Shame on you Mega.  I'll be switching to another service if you don't remove this or provide a way to disable it.

**Comment by eric-tucker** [comment]
Please provide a link to download the previous version.  I don't want these garbage pins I can't get rid of.

**Comment by shravan2x** [comment]
From https://github.com/meganz/MEGAsync/issues/72 apparently, but @naseweis520 and @ievgen-baida have made it pretty clear that a toggle is needed.

**Comment by vtmateos** [comment]
Thank you for your feedback.

We already thought that many users could want to remove those icons so we implemented a way to remove them. It's just needed to right-click on the icon or on the root of a synced folder in the File Explorer of Windows and select the new "Remove from the left pane" option in the drop-down menu. It's needed that MEGAsync is running in order to see and use that option. After the autoupdate, Windows Explorer keeps the previous version of the shell extesion loaded, so it's needed to restart Windows Explorer or reboot the computer in order to force Windows Explorer to load the new version of the shell extension with the new option.

Sorry for the inconvenience.

**Comment by shravan2x** [comment]
@vtmateos I was able to get this working. I just hadn't restarted since the update.
