### ISSUE TITLE
nautilus-megasync emblems have low resolution

### ISSUE THREAD

**Issue by alex94puchades** [meganz/MEGAsync#93]
Could you please increase the resolution of the emblems in nautilus-megasync? They look quite blurry in my system. Thank you.

**Comment by polmr** [comment]
Thanks for pointing that out, we'll work on that :-)

**Comment by EliaGeretto** [comment]
This problem is also present on Fedora 26, GNOME 3.24.2, Files (Nautilus) 3.24.2.1. Obviously not a critical issue, but it would be nice if it was fixed.
![screenshot from 2017-09-11 22-30-37](https://user-images.githubusercontent.com/9071002/30295445-eb763e62-9740-11e7-8763-cc8b45d0a4a5.png)
![screenshot from 2017-09-11 22-33-03](https://user-images.githubusercontent.com/9071002/30295545-3e612c7c-9741-11e7-908a-66e5e39e9ca4.png)

**Comment by polmr** [comment]
The issue occurs in all OSs. We will eventually fix that. Thanks for the reminder ;-)

**Comment by polmr** [comment]
A new version has been released with updated icons.
