### ISSUE TITLE
Windows 11 can't upload files

### ISSUE THREAD

**Issue by uroboloss** [meganz/MEGAsync#958]
I'm trying to sync some folders between two devices at the moment. One of them is my main desktop running Windows 10 and the other is a laptop running Windows 11. MegaSync is in the latest version in both devices.

I have no problems with the desktop, everything I do within the desired folders is uploaded to the cloud. The problem is with the laptop, it will download files to keep them updated but it won't upload any files. Mega does recognize that there are files that should be synced and it tries to do so, they will quickly be shown as "completed" in the transfer manager window and then it will try to upload them again, this keeps happening in a loop.

I wanted to have those folders synced between both devices so I can seemingless switch between them and work from any of the two devices. Right now whatever work I do in the laptop is stuck there untill I copy it to a flash drive and then to my desktop.

**Comment by tt-mega** [comment]
Hi there,

If you wish to sync one folder between multiple computers, please ensure you are logged into the same account on every computer and follow these steps:

Computer 1: set up a local sync folder A (from your local drive) to a remote folder A1 (in MEGA Cloud drive);
Computer 2: set up the remote sync folder A1 (from MEGA Cloud drive) to a local synced folder B (in your local drive).

Then you can edit directly in your local folder A and local folder B.

The Desktop app will check the latest changes and update your files/folders to the latest version of them based on the most recent change.

PLEASE NOTE: Always check the timestamp of your files before syncing if you want to avoid possible re-upload/download problems.
In fact, moving or copying files between different file systems (FAT, NTFS, exFat, ...) could cause variations in the modification date (timestamp). If it happens, the Desktop app will interpret that there are updated files and it will upload/download them again.
So, if you want to physically copy already synced data to another machine, please check the timestamp of the original files and the timestamp of the copied file.
If they match, there should be no problem and no sync action is needed. You can just move the copied files into the local synced folder.

If you have any issues during multiple computer synchronisation:

- Be careful when you are editing a file from multiple computers at the same time. If possible, wait until file changes are synced before modifying it from another location in order to avoid sync issues.
- Be aware that if you work with computers with different time zone configurations or different times, the most recent file will overwrite the others. Before you start syncing files between multiple computers be sure that your time configurations are correct.
- Check if the timestamp of your files in the local synced folder A, has the same timestamp of the local synced folder B.
- Another problematic area may be the file system you are using.

FAT / FAT 32
While it may appear to work at first glance, we strongly advise against it, because FAT timestamps are timezone dependent, resulting in all of your files being re-synced twice a year if you live in an area observing daylight saving time. Unfortunately, the following fundamental design flaw in the Windows API design makes it difficult to dynamically compensate for such changes: "When it becomes daylight saving time, the time retrieved by GetFileTime is off an hour, because the cache is not updated. When you restart the computer, the cached time that GetFileTime retrieves is correct."

For more information, please visit: https://help.mega.io/installs-apps/desktop-syncing/fat-fat32

**Comment by uroboloss** [comment]
Thanks for the reply!

I had the folders set to "backup" on the desktop, I've changed them to "sync" and now everything seems to be working the way I want. Both devices are picking up the most recent version of the files and also uploading them whenever I make changes.

**Comment by uroboloss** [comment]
Thanks for the reply!

I had the folders set to "backup" on the desktop, I've changed them to "sync" and now everything seems to be working the way I want. Both devices are picking up the most recent version of the files and also uploading them whenever I make changes.
