### ISSUE TITLE
v3.0.1.0: don't login

### ISSUE THREAD

**Issue by SergeyDjam** [meganz/MEGAsync#97]
I run megasync, 
Enter my login (email) and password, and push next button and http://i.imgur.com/o1xOKUn.png end

No working login. What fix it problem?

technical report:
ROSA Desktop Fresh R8.1 release 2014.1 for x86_64
Qt 5.6.1
MEGASync 3.0.1 (bba566)

**Comment by polmr** [comment]
Can you do it now? btw, there is a 3.1.2 megasync version for all supported platforms

**Comment by SergeyDjam** [comment]
https://github.com/meganz/MEGAsync/releases i don't find this release

**Comment by polmr** [comment]
my mistake. apologies. 3.1.2 will be pushed here soon. Is 3.0.1 logging fine now?

**Comment by SergeyDjam** [comment]
Oh, no. 3.0.1 don't logging now. I hope 3.1.2 will be working.

**Comment by polmr** [comment]
ok :-(, it seems an issue with your client @SergeyDjam.
Could you please generate a log so that we can determine what's happening. 
In order to do so: please close MEGAsync, and run it in a terminal in this way:

megasync --debug > log.txt

Since the log could contain sensitive data (mainly file names) it would be better if you 
send it to support@mega.nz along with the the URL of this issue on GitHub. 
That way, the report should reach the developmenent team fast and we would carefully review it.

**Comment by SergeyDjam** [comment]
send message

**Comment by polmr** [comment]
Solved after recompiling with proper version of the SDK and curl
