### ISSUE TITLE
Mega for Mac App cannot be opened on the BIGSUR of the Internet chip

### ISSUE THREAD

**Issue by routuanfusiji** [meganz/MEGAsync#974]
<img width="1539" alt="image" src="https://github.com/user-attachments/assets/a52ca749-7c7f-4306-828f-6c4e683a1a9a">

mega app version number: 5.4
Mac's version number: bigsur
Chip: Intel

**Comment by rautamiekka** [comment]
See if it gives you any messages when you start the app in the terminal.

**Comment by routuanfusiji** [comment]
I still can't start it, there is no error message

**Comment by mgmhunt** [comment]
same OS 10.13.6 machine - no icon in menubar, no sync icons in finder  but processes appear to be running.  previous version worked fine on this OS/machine.

Ventura 13 machine works.

**Comment by routuanfusiji** [comment]
It seems that everyone has encountered similar problems

**Comment by vtmateos** [comment]
Thanks for reporting, our devs are investigating the possible issue. It seems a problem with some libs on 5.3+ versions.

In order to have a working workaround, please remove MEGAsync from login items in system settings as follows:
<img width="470" alt="Screenshot 2024-07-26 at 12 43 12" src="https://github.com/user-attachments/assets/f41882da-6f3d-4d27-b944-7822eb00e24b">

Restart the system and install 5.2.1 version from [here](https://mega.nz/file/UlYgmBTC#UuCjeHhNzAfQ1b4yzteDx30bHZ7MQNpnU74PjKk5KSs)

Apologies for the inconveniences, we will keep you updated with any progress on this regard. Thanks.

**Comment by vtmateos** [comment]
New update: Issue was fixed and will be available on next 5.4.1 version in the following days. Apologies.
